repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check .
        language: system
        types: [python]

      - id: isort
        name: isort (python)
        entry: isort --check .
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8
        language: system
        types: [ python ]
        require_serial: true

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.0
    hooks:
      - id: poetry-check
